---
- name: Rocky Linux install block
  become: true
  block:
    - name: Import rpm key from a influx
      ansible.builtin.rpm_key:
        state: present
        key: https://repos.influxdata.com/influxdb2.key
      become: true

    - name: put a influxdb repo config file into the dnf repo
      ansible.builtin.copy:
        src: influxdata.repo
        dest: /etc/yum.repos.d/influxdata.repo

    - name: "Get {{ package }}} package"
      become: true
      ansible.builtin.dnf:
        update_cache: true
        name: "{{ package }}"
      register: pkg_install_result
