---
telgraf2influxdb_configs:
  localhost:
    url: "http://127.0.0.1"
    token: ""
    bucket: "{{ influx_default_bucket }}"
    org: "{{ influx_org }}"
    namedrop: '["influxdb_oss"]'
    bucket_tag: ""
    exclude_bucket_tag: ""
    ping_timeout: "0s"
    read_idle_timeout: "0s"
    insecure_skip_verify: false
  sample:
    url: "http://monitor.{{ domain }}"
    token: YOUR_TOKEN_GOES_HERE
    bucket: "{{ influx_default_bucket }}"
    org: "{{ influx_org }}"
    namedrop: '["influxdb_oss"]'
    bucket_tag: ""
    exclude_bucket_tag: false
    ping_timeout: "0s"
    read_idle_timeout: "0s"
    insecure_skip_verify: false
