---
dependency:
  name: galaxy
  options:
    requirements-file: ../../molecule/shared/requirements.yml
    ignore-errors: true

driver:
  name: default

# Define test VM in platforms section
platforms:
  - name: "uut-vm"
    template: "MUST_BE_SET" # Intentionally no default - fail if PROXMOX_TEMPLATE unset

provisioner:
  name: ansible
  log: true
  playbooks:
    # create: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | dirname | dirname }}/molecule/shared/proxmox/create.yml"
    # prepare: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | dirname | dirname }}/molecule/shared/proxmox/prepare.yml"
    # destroy: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | dirname | dirname }}/molecule/shared/proxmox/destroy.yml"
    create: "../../../../molecule/shared/proxmox/create.yml"
    prepare: "../../../../molecule/shared/proxmox/prepare.yml"
    destroy: "../../../../molecule/shared/proxmox/destroy.yml"
  config_options:
    defaults:
      roles_path: roles
      interpreter_python: auto_silent
      host_key_checking: false
  inventory:
    group_vars:
      all:
        proxmox_vmid: "{{ lookup('env', 'PROXMOX_VMID') | int }}"
        proxmox_template: "{{ lookup('env', 'PROXMOX_TEMPLATE') }}"
        proxmox_vm_name: "uut-vm"
        molecule_ip: "{{ lookup('env', 'MOLECULE_IP') }}"

        project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        report_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | dirname | dirname }}/verify_output"
    host_vars:
      uut-vm:
        ansible_host: "{{ lookup('env', 'MOLECULE_IP') }}"
        ansible_connection: ssh
        ansible_user: "${USER}"

        alloy_loki_endpoint: "127.0.0.1"

scenario:
  name: proxmox
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: ansible
