---
# Agent state control
fail2ban_state: present # Options: present, configure, absent

# Deployment profile - determines default security and logging settings
# Options: default, ispconfig
fail2ban_jail_profile: "default"

# Smell, default to false and do better on key
fail2ban_abuseipdb_enabled: false

fail2ban_abuseipdb_api: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62393061653461643735623161653439313966373033343433656266373932313331336330663933
  6230386236363438353135636235336334326230303163360a656137666363636336663862643831
  65616434333633343465303166396630393737333135636539333332383065353032633663326437
  6633616439613131310a396461383830633030663336623730646234396532393737323435323165
  62313935353362353530333035373637653737363633366138383632363662636232353033613039
  30623132333439313735643837383439663732313738396231626632396661303663636162613331
  36333365396530303637616263303839646434333934303163633436363539333232336130643766
  37326539353462623633366139333131633462653330623766303130303664396564653063346237
  3661

# Git versioning
fail2ban_git_versioning:
  enabled: yes
  repository_path: "/opt/solti-repo/fail2ban"
  commit_msg: "Configuration updated by Ansible on {{ ansible_date_time.iso8601 }}"
  manage_repository: yes # Should the role create/init the git repo if missing?

# Main fail2ban configuration
# Claude:  fix the fail2ban.local.j2 to allow these as optional arguments
# I want to keep the system defaults where I need to (like log level and allow_ipv5 )
fail2ban_config:
  loglevel: INFO
  allowipv6: auto
  logtarget: /var/log/fail2ban.log
  syslogsocket: auto
  socket: /var/run/fail2ban/fail2ban.sock
  pidfile: /var/run/fail2ban/fail2ban.pid
  dbfile: /var/lib/fail2ban/fail2ban.sqlite3
  dbpurgeage: 86400 # 1 day
  dbmaxmatches: 10

# Default jail settings taken from angela
fail2ban_jail_defaults:
  ignoreip: 127.0.0.1/8 ::1
  bantime: 60m
  findtime: 30m
  maxretry: 3
  bantime_increment: true
  bantime_rndtime: 30m
  bantime_maxtime: 30d
  bantime_factor: 3
  bantime_overalljails: true

# All jails are in the jail.d directory and managed by profile

# This a is a dictionary of capability groups than may be configured.
# It includes jails and the filters

fail2ban_jails:
  base:
    enabled: true
    description: "Core protection for SSH and repeat offenders"
    jails:
      - sshd.conf
      - recidive.conf
  ispconfig:
    enabled: false
    description: "ISPconfig services protection"
    jails:
      - apache-default.conf
      - ispconfig-apache.conf
      - mail-svc.conf
      - pure-ftpd.conf
    filters:
      - apache-4xx.conf
      - apache-auth.conf
      - apache-malicious.conf
      - named-amplification.conf
      - named-ddos.conf
      - named-denied-custom.conf
  gitea:
    enabled: false
    description: "Code repository protection"
    jails:
      - gitea.conf
    filters:
      - gitea.conf
  openvpn:
    enabled: false
    description: "Openvpn server protection"
    jails:
      - openvpn.conf
    filters:
      - openvpn.conf
      - openvpn-standalone.conf
  ufw:
    enabled: false
    description: "Network protection"
    jails:
      - ufw-probe.conf
    filters:
      - ufw-probe.conf
  wordpress:
    enabled: false
    description: "Wordpress protection"
    jails:
      - wordpress.conf
    filters:
      - wordpress.conf
      - wordpress-extra.conf
      - wordpress-hard.conf
      - wordpress-soft.conf
      - wordpress-vhost.conf
      - wp-exploits.conf

#............................................
fail2ban_custom_filters:
  - apache-4xx.conf
  - apache-auth.conf
  - apache-malicious.conf
  - gitea.conf
  - named-amplification.conf
  - named-ddos.conf
  - named-denied-custom.conf
  - openvpn.conf
  - openvpn-standalone.conf
  - ufw-probe.conf
  - wordpress.conf
  - wordpress-extra.conf
  - wordpress-hard.conf
  - wordpress-soft.conf
  - wordpress-vhost.conf
  - wp-exploits.conf

# Services that should be automatically enabled and started
fail2ban_services:
  - fail2ban
