galaxy_info:
  author: jackaltx
  description: Install/remove Loki
  company: lavnet.net
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "9"

  galaxy_tags: []
  # List tags for your role here, one per line. A tag is a keyword that describes
  # and categorizes the role. Users find roles by searching for tags.
  # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
  # Maximum 20 tags per role.

dependencies: []
# List your role dependencies here, one per line.
