---
- name: Total Removal
  hosts: monitor2

  vars:
    influxdb_state: absent
    influxdb_delete_config: true
    influxdb_delete_data: true

    telegraf_state: absent
    telegraf_delete_config: true
    telegraf_delete_data: true

    alloy_state: absent
    alloy_delete_config: true
    alloy_delete_data: true

    loki_state: absent
    loki_delete_config: false
    loki_delete_data: false

  roles:
    # clients
    - telegraf
    - alloy

    # services
    - influxdb
    - loki
